name: Release helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "deploy/eero-metrics/*"

jobs:
  release-chart:
    permissions:
      contents: write
    uses: imdevinc/imdevinc/.github/workflows/shared-chart-release.yaml@v1
    with:
      chart-dir: deploy
    secrets: inherit